<template>
  <div class="loadingio-spinner-spinner-dqftwil5nh6">
    <div class="ldio-f70jlx6pfqb">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-f70jlx6pfqb {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-f70jlx6pfqb div {
  left: 40px;
  top: 6px;
  position: absolute;
  animation: ldio-f70jlx6pfqb linear 0.5681818181818182s infinite;
  background: #000000;
  width: 20px;
  height: 20px;
  border-radius: 10px / 10px;
  transform-origin: 10px 44px;
}
.ldio-f70jlx6pfqb div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.4971590909090909s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(2) {
  transform: rotate(45deg);
  animation-delay: -0.42613636363636365s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(3) {
  transform: rotate(90deg);
  animation-delay: -0.35511363636363635s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(4) {
  transform: rotate(135deg);
  animation-delay: -0.2840909090909091s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(5) {
  transform: rotate(180deg);
  animation-delay: -0.21306818181818182s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(6) {
  transform: rotate(225deg);
  animation-delay: -0.14204545454545456s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(7) {
  transform: rotate(270deg);
  animation-delay: -0.07102272727272728s;
  background: #000000;
}
.ldio-f70jlx6pfqb div:nth-child(8) {
  transform: rotate(315deg);
  animation-delay: 0s;
  background: #000000;
}
.loadingio-spinner-spinner-dqftwil5nh6 {
  width: 32px;
  height: 32px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-f70jlx6pfqb {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.32);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-f70jlx6pfqb div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
